/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Example.Thrift.Types
{
  /// <summary>
  /// Состояние диалога.
  /// </summary>
  public enum DialogState
  {
    ENQUEUED = 0,
    OPENED = 1,
    CLOSED = 2,
    REOPENED = 2,
  }
}
