/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package example.thrift.types;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Состояние диалога.
 */
public enum DialogState implements org.apache.thrift.TEnum {
  ENQUEUED(0),
  OPENED(1),
  CLOSED(2),
  REOPENED(2);

  private final int value;

  private DialogState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DialogState findByValue(int value) { 
    switch (value) {
      case 0:
        return ENQUEUED;
      case 1:
        return OPENED;
      case 2:
        return CLOSED;
      case 2:
        return REOPENED;
      default:
        return null;
    }
  }
}
