/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package example.thrift.types;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Статус участника диалога.
 */
public enum SubjectStatus implements org.apache.thrift.TEnum {
  OFFLINE(0),
  ONLINE(1);

  private final int value;

  private SubjectStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SubjectStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return OFFLINE;
      case 1:
        return ONLINE;
      default:
        return null;
    }
  }
}
