/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Example.Thrift.Types
{
  /// <summary>
  /// Статус участника диалога.
  /// </summary>
  public enum SubjectStatus
  {
    OFFLINE = 0,
    ONLINE = 1,
  }
}
